#!/bin/bash
cp casp_selected_domains/T0693-D2.pdb casp_test_cases
cp casp_selected_domains/T0719-D2.pdb casp_test_cases
cp casp_selected_domains/T0719-D4.pdb casp_test_cases
cp casp_selected_domains/T0719-D5.pdb casp_test_cases
cp casp_selected_domains/T0726-D2.pdb casp_test_cases
cp casp_selected_domains/T0726-D3.pdb casp_test_cases
cp casp_selected_domains/T0734-D1.pdb casp_test_cases
cp casp_selected_domains/T0761-D2.pdb casp_test_cases
cp casp_selected_domains/T0771-D1.pdb casp_test_cases
cp casp_selected_domains/T0777-D1.pdb casp_test_cases
cp casp_selected_domains/T0781-D2.pdb casp_test_cases
cp casp_selected_domains/T0785-D1.pdb casp_test_cases
cp casp_selected_domains/T0789-D1.pdb casp_test_cases
cp casp_selected_domains/T0790-D1.pdb casp_test_cases
cp casp_selected_domains/T0794-D1.pdb casp_test_cases
cp casp_selected_domains/T0808-D1.pdb casp_test_cases
cp casp_selected_domains/T0808-D2.pdb casp_test_cases
cp casp_selected_domains/T0810-D1.pdb casp_test_cases
cp casp_selected_domains/T0814-D1.pdb casp_test_cases
cp casp_selected_domains/T0814-D2.pdb casp_test_cases
cp casp_selected_domains/T0824-D1.pdb casp_test_cases
cp casp_selected_domains/T0810-D2.pdb casp_test_cases
cp casp_selected_domains/T0831-D1.pdb casp_test_cases
cp casp_selected_domains/T0832-D1.pdb casp_test_cases
cp casp_selected_domains/T0837-D1.pdb casp_test_cases
cp casp_selected_domains/T0858-D1.pdb casp_test_cases
cp casp_selected_domains/T0861-D1.pdb casp_test_cases
cp casp_selected_domains/T0862-D1.pdb casp_test_cases
cp casp_selected_domains/T0863-D1.pdb casp_test_cases
cp casp_selected_domains/T0866-D1.pdb casp_test_cases
cp casp_selected_domains/T0870-D1.pdb casp_test_cases
cp casp_selected_domains/T0886-D1.pdb casp_test_cases
cp casp_selected_domains/T0886-D2.pdb casp_test_cases
cp casp_selected_domains/T0892-D1.pdb casp_test_cases
cp casp_selected_domains/T0900-D1.pdb casp_test_cases
cp casp_selected_domains/T0912-D1.pdb casp_test_cases